### PR TITLE
feature: upgrade to tx-edc 0.7.3 (upstream edc 0.7.1)

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

Align code and charts with the upstream projects.

## WHY

Agent Plane (Extension) needs to be compatible to the CX 24.08 base/control plane.

## FURTHER NOTES

Deps upped ... flyway version seems not to have been IP checked yet.

Closes #92 <-- _insert Issue number if one exists_

### CODE REVIEW

**Review by obalandi — APPROVED** [review]
LGTM! The Ubgrades appear complete.

**Comment by almadigabor** [comment]
Hey @drcgjung, the IP issue is created and can be tracked [here](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15692).

**Comment by drcgjung** [comment]
> Hey @drcgjung, the IP issue is created and can be tracked [here](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15692).

And it has been already approved! We need to give Rahul credit on his reaction time.

**Comment by almadigabor** [comment]
Hi @drcgjung, could you please update the DEPENDENCIES file here as well? A restricted library have been approved.

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
