### PR TITLE
PRIO-2 fix: deal with peculiarities of the EDC 0.5.1 control plane 

### LINKED ISSUE #83: Agent Plane would not delegate remote skills and graphs when used in conjunction with EDC Control Plane 0.5.1
## As-Is

When upgrading the EDC control plane to tag "0.5.1" (all agent-connector charts), remote skills and graph delegations would result in failed agreements (and hence empty result bindings).

## As-Should

Agent Plane should work seamlessly with EDC 0.5.1

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

see #83 the current agent plane is bound to EDC 0.5.0

We mediate the switch to the subtle "NON"-changes of EDC 0.5.1 (negotiation request: two fields switched roles; transfer request: due to lacking StatusCheckers the process won't over reach state COMPLETED, but stay in STARTED) by allowing the data plane to know with which version of the control plane it interacts.

## WHY

We need to be able to upgrade to EDC 0.5.1 and beyond.

## FURTHER NOTES

should wait for PR #86 to become green

Closes #83

### CODE REVIEW

**Review by carslen — APPROVED** [review]
LGTM

@drcgjung can you or an other dev give a technical approval here as I cannot assess the changes.

**Comment by carslen** [comment]
Please review failing Check.

**Comment by drcgjung** [comment]
> Please review failing Check.

merge with the PRIO-1 PR/merge did the job. Asked @TomBuchertTSystems for a technical review ...

**Review by Martin0815bla — APPROVED** [review]

**Comment by carslen** [comment]
2nd review available, merging PR now

**Pull request merged**
