### PR TITLE
feat: extend federated catalogue to allow for goal-oriented skills

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

This feature extends the federated catalogue and the associated synchronization process to store and reference about extended asset meta-data including shacl constraints to describe the graph shapes.

## WHY

Using the extended catalogue triples makes it possible to implement goal-oriented skills which reason about the assets before negotiating/jumping into the actual data. The present implementation has been test-driven using two formerly separate skills from the Behaviour Twin Use case.

Furthermore the federated catalogue is now also aligned with the CX-0018 standard properties of assets.

## FURTHER NOTES

Closes # <-- _insert Issue number if one exists_

### CODE REVIEW

**Comment by drcgjung** [comment]
@almadigabor I will inform you once Oz and Martin have successfully reviewed the changes from the business and technical side. It would be nice if you could take that over, then.

**Review by Martin0815bla — APPROVED** [review]
Changes regarding formatting, constant introduction, allow/deny pattern, new methods and tests reviewd

**Comment by drcgjung** [comment]
> Changes regarding formatting, constant introduction, allow/deny pattern, new methods and tests reviewd

@Martin0815bla  sorry had to update some copyright periods as well.

**Review by Martin0815bla — APPROVED** [review]
Changes regarding formatting, constant introduction, allow/deny pattern, new methods,  tests and copyright periods reviewed

**Review by obalandi — APPROVED** [review]
Everything looks fine

**Comment by drcgjung** [comment]
@almadigabor could you please take over, then? Thx!

**Review by almadigabor — APPROVED** [review]
LGTM

**Pull request merged**
