### PR TITLE
feat:CXAR-921 Agent Plane Code Overtake

### PR DESCRIPTION
**Pull request by drcgjung**
## Description

Overtakes code from catenax-ng/product-agents-edc
Fixes https://jira.catena-x.net/browse/KA-324

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up to date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] Copyright and license header are present on all affected files

### Additional information

- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and committers
- Use the [mailing list](https://accounts.eclipse.org/mailing-list/tractusx-dev) if you are unsure, who to contact, or if want to engage in a general discussion
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)
- Check out the [Eclipse Foundation contribution guidelines](https://www.eclipse.org/projects/handbook/#contributing)

### CODE REVIEW

**Review by carslen — CHANGES_REQUESTED** [review]
Needs clarification regarding license and copyright header, as mentioned in eclipse-tractusx/knowledge-agents#1

**Comment by drcgjung** [comment]
For the IP check

maven/mavencentral/org.apache.jena/jena-fuseki-core/4.8.0, , restricted, clearlydefined
see https://github.com/apache/jena/blob/main/LICENSE

**Comment by Siegfriedk** [comment]
Initial Contribution check ticket is created here: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9836

**Comment by Siegfriedk** [comment]
IP ticket is through. We need a rerun of DEPENDENCIES file for this restricted library maven/mavencentral/org.apache.jena/jena-fuseki-core/4.8.0, , restricted, clearlydefined and potentially an IP ticket before we can merge it.

All other comments from our side will be revalidatedin the QG4

**Comment by SebastianBezold** [comment]
Hi @drcgjung,

I was just trying to create the automated IP issues using Dash licence tool. When generating the input for dash via 
`mvn --settings settings.xml dependency:list -DskipTests -Dmaven.javadoc.skip=true -DappendOutput=true -DoutputFile=maven.deps', I get the following error (same without the custom settings.xml from the repo):

```
[ERROR] Failed to execute goal on project agentplane-azure-vault: Could not resolve dependencies for project org.eclipse.tractusx.agents.edc.agent-plane:agentplane-azure-vault:jar:1.9.5-SNAPSHOT: The following artifacts could not be resolved: org.eclipse.tractusx.agents.edc.agent-plane:agent-plane-protocol:jar:1.9.5-SNAPSHOT (absent), org.eclipse.tractusx.edc:auth-jwt:jar:1.9.5-SNAPSHOT (absent): Could not transfer artifact org.eclipse.tractusx.agents.edc.agent-plane:agent-plane-protocol:jar:1.9.5-SNAPSHOT from/to edc (https://maven.pkg.github.com/eclipse-tractusx/tractusx-edc): status code: 401, reason phrase: Unauthorized (401)
```

could you either investigate the issue or provide a maven.deps file for dash input, that I can create the automated IP issues?

**Comment by drcgjung** [comment]
> Hi @drcgjung,
> 
> I was just trying to create the automated IP issues using Dash licence tool. When generating the input for dash via `mvn --settings settings.xml dependency:list -DskipTests -Dmaven.javadoc.skip=true -DappendOutput=true -DoutputFile=maven.deps', I get the following error (same without the custom settings.xml from the repo):
> 
> ```
> [ERROR] Failed to execute goal on project agentplane-azure-vault: Could not resolve dependencies for project org.eclipse.tractusx.agents.edc.agent-plane:agentplane-azure-vault:jar:1.9.5-SNAPSHOT: The following artifacts could not be resolved: org.eclipse.tractusx.agents.edc.agent-plane:agent-plane-protocol:jar:1.9.5-SNAPSHOT (absent), org.eclipse.tractusx.edc:auth-jwt:jar:1.9.5-SNAPSHOT (absent): Could not transfer artifact org.eclipse.tractusx.agents.edc.agent-plane:agent-plane-protocol:jar:1.9.5-SNAPSHOT from/to edc (https://maven.pkg.github.com/eclipse-tractusx/tractusx-edc): status code: 401, reason phrase: Unauthorized (401)
> ```
> 
> could you either investigate the issue or provide a maven.deps file for dash input, that I can create the automated IP issues?

Since the build has not yet run on the target maven repo, you need to "install" in addition. Since its a multi-module pom, I guess you need to make the target file absolute:

' mvn --settings settings.xml dependency:list -DskipTests -Dmaven.javadoc.skip=true -DappendOutput=true -DoutputFile=$(pwd)/maven.deps'

works on my Mac.

I'll send you the file (and a fresh DEPENDENCIES) via email, ok?

**Comment by SebastianBezold** [comment]
Hi @drcgjung,

ok ok I indeed didn't run a install first. With the `maven.deps` you sent me only the following issue was created:

- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9841

so as soon as this is processed, you can generate the `DEPENDENCIES` again. Using the maven plugin should produce the same output as running Dash plainly

**Comment by drcgjung** [comment]
[INFO] Querying Eclipse Foundation for license data for 89 items.
[INFO] Found 71 items.
[INFO] Querying ClearlyDefined for license data for 18 items.
[INFO] Found 18 items.
[INFO] Vetted license information was found for all content. No further investigation is required.

**Comment by drcgjung** [comment]
@carslen could you please merge this initial contribution pre-QG4 ... otherwise we will not be able to run some of the required QG4 checks (the cat and her tail ...) Thx.

**Comment by Siegfriedk** [comment]
ip check and dep are fixed. merging it for pre qg4

**Pull request merged**
