### PR TITLE
Chore: Prepare TX 2412 E2E tests

### LINKED ISSUE #245: Remove all Catena-X (NG) references
This issue tracks the removal of all occurrences of `CatenaX-ng` in this repository as part of the broader goal to deprecate this organization.

- [ ] Search for `Catena-X (NG)` in code, configuration, and documentation.
- [ ] Remove or adapt references accordingly.
- [ ] Close this issue once zero references remain.

Use this query to track your progress (overall): [GitHub Search Query](https://github.com/search?q=repo%3A[RepoName]+catenax-ng&type=code)

[This](https://github.com/search?q=org%3Aeclipse-tractusx+catenax-ng+repo%3Aeclipse-tractusx%2Fknowledge-agents-edc&type=code) query should display only results in related repository

Work summarized in https://github.com/eclipse-tractusx/sig-release/issues/838

### LINKED ISSUE #246: [Trufflehog Update] Add Trufflehog secret scanning workflow
## Description

The GitGuardian secret scanning tool licence is now expired, therefore in order to maintain the Security of the Tractus-X Repositories there will be inforced the [TRG-8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) for all Tractus-X repos.

## Incident Ticket

https://github.com/eclipse-tractusx/sig-security/issues/86

Your repository was found in one of our security scans, and it was listed along with other repositories for not contain any of this files:

```md
".github/workflows/trufflehog.yaml"
".github/workflows/trufflehog.yml"
".github/workflows/secrets-scan.yml"
```

Please read the [TRG-8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) and create the workflow file as soon as posible!

## What needs to be done?

- [ ] Add the Trufflehog workflow like described in [TRG-8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) to the `/.github/workflows` folder
- [ ] Remove all references to GitGuardian from documentation
- [ ] Create a PR and Merge it to `main`
- [ ] As committer: revise if any secrets were found in the scan (in the security tab)
- [ ] Close this ticket

Thank you very much for doing the update! 🚀

If there is any question, please let us know,  
Your Tractus-X Project Leads 💯

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

Contains all version and dependency updates necessary to enter the E2E phase of TX/CX 2412 release.
Also checked with latest TRGs and issues around that.

## WHY

We need to synchronize against TX EDC 0.8.0-rc4 (und its upstream snapshot).
At the same time we mitigate new CVEs and care for the TRGs.

## FURTHER NOTES

Closes #246 
Closes #245

### CODE REVIEW

**Review by almadigabor — COMMENTED** [review]
Looks good, although a release can't be created until all the dependencies are approved. I created the following issues for the Eclipse IP team to check licences. Once they are approved, the DEPENDENCIES file should be updated.

```
[INFO] License information could not be automatically verified for the following content:
[INFO] 
[INFO] maven/mavencentral/com.fasterxml.jackson.dataformat/jackson-dataformat-toml/2.18.0
[INFO] maven/mavencentral/org.flywaydb/flyway-database-postgresql/10.18.0
[INFO] 
[INFO] This content is either not correctly mapped by the system, or requires review.
[INFO] A review is required for maven/mavencentral/com.fasterxml.jackson.dataformat/jackson-dataformat-toml/2.18.0.
[INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16800 .
[INFO] A review is required for maven/mavencentral/org.flywaydb/flyway-database-postgresql/10.18.0.
[INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16801 .
```

**Comment by almadigabor** [comment]
Hey @drcgjung, All dependencies have been approved. I don't have permissions to push to you branch so please update the DEPENDENCIES file and then I can merge this PR.

**Comment by drcgjung** [comment]
> Hey @drcgjung, All dependencies have been approved. I don't have permissions to push to you branch so please update the DEPENDENCIES file and then I can merge this PR.

@almadigabor DEPs have been updated an look good. EDC 0.8.0-rc5 has just been released, but we do not restest (75 integration and e2e tests) so we wait for the final release to upgrade.

**Review by obalandi — APPROVED** [review]
LGTM

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
